services:
  - type: web
    name: coffee-bean-detector
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB_USER
        fromDatabase:
          name: coffeebean
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: coffeebean
          property: password
      - key: DB_HOST
        fromDatabase:
          name: coffeebean
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: coffeebean
          property: database

databases:
  - name: coffeebean
    databaseName: coffeebean_scanner_db
    plan: free
    ipAllowList: [] 